### ISSUE TITLE
PROVIDING THE DATE MUST BE DISCONTINUED IMMEDIATELY

### ISSUE THREAD

**Issue by crossm0d** [shwoop/laamaj#15]
STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT STOP IT 

IT IS NOT FUNNY IT NEVER WAS

**Comment by shwoop** [comment]
I don't see a pull request
